### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by Toub** [js-data/js-data-http#13] opened 2015-05-15 11:51 UTC
I am using js-data to communicate between 2 nodejs applications.

js-data-http 1.2.3 does not work anymore with nodejs, while v1.1.0 does.

The error is: "ReferenceError: navigator is not defined"

I can't figure who throws the error. Maybe axios?

The error was hidden by an other issue in js-data-http:

     function logResponse(data) {
        var str = start.toUTCString() + ' - ' + data.config.method.toUpperCase() + ' ' + data.config.url + ' - ' + data.status + ' ' + (new Date().getTime() - start.getTime()) + 'm

In case of error from the server (e.g. wrong url), data.config is not defined.

**Comment by jmdobry** [comment] 2015-05-15 22:25
It may be an issue with how axios is bundled with js-data-http.

**Comment by tmoitie** [comment] 2015-05-18 14:30
Just FYI, this is the error that lead me to find issue #12, so yes.

**Comment by jmdobry** [comment] 2016-01-10 22:43
Duplicate of #12

**Closed by jmdobry** 2016-01-10 22:43 UTC
Labels: bug
