### ISSUE TITLE
js-data-http does not work with React Native in a mobile environment

### ISSUE THREAD

**Issue by aveerthakur** [js-data/js-data-http#32] opened 2015-12-08 18:55 UTC
Your framework currently runs in a browser and Node. We are experimenting with mobile apps with something like React Native  which is closer to a browser but does not have all the polyfills. I had to comment out a few cookie/document/navigator references in you 'js-data-http' adapter to make it work. Please consider this 3rd environment - the delta in terms of code changes is not big but you can fulfill the needs of a big emerging category of apps.

**Comment by zuzusik** [comment] 2015-12-09 11:08
Isn't it possible to include required polyfills into React Native app?

**Comment by aveerthakur** [comment] 2015-12-09 17:32
React Native currently has a limited set of polyfills: https://facebook.github.io/react-native/. If you treat 'js-data-http' as a blackbox you will not know what works and what does not in that environment. You will have to depend on hit and trials. Intentionally designing js-data to run on React Native would lead the code to be either not dependent or optionally dependent on  things like: cookie/navigator/document etc.

**Comment by gutenye** [comment] 2015-12-10 03:46
:+1: for this

The problem is js-data-http depends 3rd part library: axios, which does not work in React Native.

React Native support `fetch()` and `XMLHttpRequest()`, either one is enough to make the js-data-http adapter works.

**Comment by gutenye** [comment] 2015-12-10 04:01
Turns out [axios 0.7 is already support React Native](https://github.com/mzabriskie/axios/commit/6aa766e5e92688dc8946902907dbcd3ee9278767), I think just update the axios dependency version will work.

**Comment by jmdobry** [comment] 2016-01-10 22:46
Fixed in 3.0.0-alpha.2. `js-data-http` 3.0.0-alpha.2 now bundles the browser build of axios v0.8.1. There is also a `js-data-http-node` package in NPM that users the Node.js build of axios v0.8.1. There is also a `js-data-fetch` package which does not bundle or use axios, and will default to using `window.fetch` if you don't provide your own http lib.

**Closed by jmdobry** 2016-01-10 22:46 UTC

**Comment by aveerthakur** [comment] 2016-01-11 03:56
:+1:  Thanks for fixing it!

**Comment by crobinson42** [comment] 2018-08-13 20:34
There is a working example of `js-data-http` working in a React Native project here: https://github.com/crobinson42/react-native-js-data-demo
