### ISSUE TITLE
Adding support for form-data 

### ISSUE THREAD

**Issue by sebastianhenneberg** [js-data/js-data-http#14] opened 2015-06-05 15:26 UTC
It would be great to have support for form-data in the httpAdapter to upload files via HTTP. Angulars `$resource` comes with this support built-in (attaching form-data and setting headers):

```javascript
var data = $resource('/data/:id', {}, {
  post: {
    method: 'POST',
    transformRequest: function(data) {
      var fd = new FormData();
      fd.append('file', data);
      return fd;
    },
    headers: {'Content-Type': undefined}
  }
};
````

**Comment by jmdobry** [comment] 2015-06-05 15:29
What is `new FormData()`? I don't see anything in the ngResource documentation for that.

**Comment by sebastianhenneberg** [comment] 2015-06-05 15:32
FormData is nothing related to AngularJS or $resource. It is a key-value wrapper for form-data which you can pass to XMLHttpRequests: https://developer.mozilla.org/de/docs/Web/API/FormData

**Comment by jmdobry** [comment] 2015-06-05 15:33
Are you using js-data + js-data-angular + Angular? Or just js-data + js-data-http?

**Comment by sebastianhenneberg** [comment] 2015-06-05 15:36
js-data + js-data-angular + Angular

**Comment by jmdobry** [comment] 2015-06-05 15:37
If using js-data + js-data-angular:

```js
DSHttpAdapter.HTTP({
  method: 'POST',
  transformRequest: function(data) {
    var fd = new FormData();
    fd.append('file', data);
    return fd;
  },
  headers: {'Content-Type': undefined }
})
```

If using js-data + js-data-http:


```js
store.getAdapter('http').HTTP({
  method: 'POST',
  transformRequest: [function(data) {
    var fd = new FormData();
    fd.append('file', data);
    return fd;
  }],
  headers: {'Content-Type': undefined }
})
```

**Comment by sebastianhenneberg** [comment] 2015-06-05 15:38
Great, thank you. I will give it a try.

**Comment by sebastianhenneberg** [comment] 2015-06-05 16:03
The definition above raises two TypeErrors:

```
TypeError: Cannot read property 'protocol' of undefined
    at urlIsSameOrigin (angular.js:17714)
    at sendReq (angular.js:10225)
    at $get.serverRequest (angular.js:9944)
    at processQueue (angular.js:14454)
    at angular.js:14470
    at Scope.$get.Scope.$eval (angular.js:15719)
    at Scope.$get.Scope.$digest (angular.js:15530)
    at Scope.$get.Scope.$apply (angular.js:15824)
    at done (angular.js:10263)
    at completeRequest (angular.js:10435)
```

```
TypeError: Cannot read property 'method' of undefined
    at logResponse (js-data-angular.js:573)
    at processQueue (angular.js:14454)
    at angular.js:14470
    at Scope.$get.Scope.$eval (angular.js:15719)
    at Scope.$get.Scope.$digest (angular.js:15530)
    at Scope.$get.Scope.$apply (angular.js:15824)
    at done (angular.js:10263)
    at completeRequest (angular.js:10435)
    at XMLHttpRequest.requestLoaded (angular.js:10376)
```

**Comment by jmdobry** [comment] 2015-06-05 17:55
I'll have to play around with it

**Comment by jmdobry** [comment] 2015-06-09 16:23
The second error in the issue was caused by the first error

What version of Angular are are you using?

**Comment by sebastianhenneberg** [comment] 2015-06-09 16:24
Angular 1.4

**Comment by jmdobry** [comment] 2015-06-09 16:30
It would appear that when Angular tries to make the request, it's missing the url. Can you post your code for making the request?

**Comment by DaHaiz** [comment] 2015-09-10 12:09
@jmdobry  i proceeded working on @sebastianhenneberg problem and came to the following solution:

```javascript
SomeDataStore.create({file: file}, {
          transformRequest: function(data) {
            var fd = new FormData();
            fd.append('file', data.file);
            return fd;
          }
      });
```

works like a charm, but you need to add a condition ```&& !(value instanceof File)``` to the following code.
Otherwise the actual ```File``` gets stripped from the data object passed in the ```transformRequest()``` and replaced by an empty ```Object```.

```javascript
	  // Return a copy of "object" with cycles removed.
	  removeCircular: function removeCircular(object) {
	    return (function rmCirc(value, ctx) {
	      var i = undefined;
	      var nu = undefined;


// !!!! ADDED  && !(value instanceof File) to the end of if
	      if (typeof value === 'object' && value !== null && !(value instanceof Boolean) && !(value instanceof Date) && !(value instanceof Number) && !(value instanceof RegExp) && !(value instanceof String) && !(value instanceof File)) {




	        // check if current object points back to itself
	        var cur = ctx.cur;
	        var parent = ctx.ctx;
	        while (parent) {
	          if (parent.cur === cur) {
	            return undefined;
	          }
	          parent = parent.ctx;
	        }

	        if (isArray(value)) {
	          nu = [];
	          for (i = 0; i < value.length; i += 1) {
	            nu[i] = rmCirc(value[i], { ctx: ctx, cur: value[i] });
	          }
	        } else {
	          nu = {};
	          forOwn(value, function (v, k) {
	            nu[k] = rmCirc(value[k], { ctx: ctx, cur: value[k] });
	          });
	        }
	        return nu;
	      }
	      return value;
	    })(object, { ctx: null, cur: object });
	  }
```

would be great to know if this change has any unknown side effects and if not push it to release.

Thanks in advance!

Simon

**Comment by jmdobry** [comment] 2015-09-10 14:51
@DaHaiz Thanks! I'll look at this tonight.

**Comment by jmdobry** [comment] 2015-09-20 23:12
This will be fixed when js-data 2.4.0 is released. See js-data/js-data#216

**Comment by DaHaiz** [comment] 2015-09-22 15:04
thanks a lot!

**Comment by jmdobry** [comment] 2015-09-23 03:41
Fixed in https://github.com/js-data/js-data/releases/tag/2.4.0

**Closed by jmdobry** 2015-09-23 03:41 UTC
Labels: bug
